<?php

namespace VideoClubBundle\Entity;

/**
 * PackageMinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageMinRepository extends \Doctrine\ORM\EntityRepository
{
}
