<?php

namespace VideoClubBundle\Entity;

/**
 * PurchasePackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasePackRepository extends \Doctrine\ORM\EntityRepository
{
}
