movie_index:
    path:   /movie/index
    defaults: { _controller: VideoClubBundle:Movie:index }

movie_list:
    path:   /movie/list/{val}
    defaults: { _controller: VideoClubBundle:Movie:list }

movie_show:
    path:   /movie/show/{id}
    defaults: { _controller: VideoClubBundle:Movie:show }

pack_index:
    path:   /pack/index/
    defaults: { _controller: VideoClubBundle:PackageMin:index }

pack_buy:
    path:   /pack/buy/{id}
    defaults: { _controller: VideoClubBundle:PackageMin:buy }