movie_index:
    path:   /movie/index
    defaults: { _controller: VideoClubBundle:Movie:index }

movie_list:
    path:   /movie/list/{val}
    defaults: { _controller: VideoClubBundle:Movie:list }

pack_index:
    path:   /pack/index/
    defaults: { _controller: VideoClubBundle:PackageMin:index }